runtime: python
env: flex

# Use eventlet as it is good for clients that use long polling
entrypoint: gunicorn -b :$PORT --worker-class eventlet -w 1 main:app

runtime_config:
  python_version: 3


# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.
manual_scaling:
  instances: 1
